services:
  - type: web
    name: diabetic-retinopathy-detector
    env: python
    region: oregon
    plan: free
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn DRDetector.wsgi:application --host 0.0.0.0 --port $PORT --workers 1 --timeout 300 --max-requests 100 --max-requests-jitter 10
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,diabetic-retinopathy-detector-c1br.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "DRDetector.settings"