services:
  - type: web
    name: diabetic-retinopathy-detector
    env: python
    region: oregon
    plan: free
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn DRDetector.wsgi:application --host 0.0.0.0 --port $PORT --workers 1 --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "DRDetector.settings"
      - key: PYTHON_VERSION
        value: "3.11.9"